%interface: show weighing effect, etc.

figure(11);
% ht  = uicontrol('Style','text', ...
%     'Position',[left1 bot7 0.5*(wid1+wid2) 2*height], ...
%     'String','Choose weighing',...
%     'BackgroundColor', akva);
% hwei = uicontrol('Style', 'popup',...
%        'String', 'normalize intensity to one|minimize nucleoli effect|exclude nucleoli',...
%        'Position', [left2 bot7 1.75*(wid1+wid2) 2*height],...
%        'BackgroundColor','w',...
%        'Callback', 'weighchoice');

%interface: start 3D analysis
htanaliz  = uicontrol('Style','Pushbutton', ...
    'Position',[left1 bot11 1.25*(wid1+wid2) 2*height], ...
    'String','analyse experiment',...
    'BackgroundColor','w',...
    'Callback','tanaliz');
