figure(11);

% strip = 260;   % width of strip under analysis
% ht  = uicontrol('Style','text', ...
%     'Position',[left1 bot5-0.5*bot14 wid1 1.5*height], ...
%     'String','Width of radial strips [nm]',...
%     'BackgroundColor', akva);
% hstrip = uicontrol('Style','edit', ...
%     'Position',[left2 bbot5-0.5*bbot16 wid2 1.5*height], ...
%     'String',num2str(strip),...
%     'BackgroundColor','w',...
%     'Callback','strip = str2num(get(hstrip,''String''));');

 bfa = 3; % factor for background   
 ht  = uicontrol('Style','text', ...
     'Position',[left1 bot9-0.5*bot14 wid1 1.5*height], ...
     'String','background factor',...
     'BackgroundColor', akva);
 hbfa = uicontrol('Style','edit', ...
     'Position',[left2 bbot9-0.5*bbot16 wid2 1.5*height], ...
     'String',num2str(bfa),...
     'BackgroundColor','w',...
     'Callback','bfa = str2num(get(hbfa,''String''));');


% avgo = 20;   
% ht  = uicontrol('Style','text', ...
%     'Position',[left1 bot5-0.5*bot14 wid1 1.5*height], ...
%     'String','Sliding Average',...
%     'BackgroundColor', akva);
% havgo = uicontrol('Style','edit', ...
%     'Position',[left2 bbot5-0.5*bbot16 wid2 1.5*height], ...
%     'String',num2str(avgo),...
%     'BackgroundColor','w',...
%     'Callback','avgo = str2num(get(havgo,''String''));');

hanalize  = uicontrol('Style','Pushbutton', ...
    'Position',[left3 bot5-0.5*bot14 0.75*(wid1+wid2) 2*height], ...
    'String','analize',...
    'BackgroundColor','w',...
    'Callback','analize');
